//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asphalt_9_Materials.ViewModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blueprint
    {
        public int id { get; set; }
        public Nullable<int> FirstStarBP { get; set; }
        public Nullable<int> SecondStarBP { get; set; }
        public Nullable<int> ThirdStarBP { get; set; }
        public Nullable<int> FourthStarBP { get; set; }
        public Nullable<int> FifthStarBP { get; set; }
        public Nullable<int> SixthStarBP { get; set; }
        public Nullable<int> TotalBP { get; set; }
    
        public virtual Grande Grande { get; set; }
    }
}
