//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asphalt_9_Materials.ViewModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public int id { get; set; }
        public int Chapter { get; set; }
        public string Season { get; set; }
        public Nullable<int> Race { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Mode { get; set; }
        public string Track { get; set; }
        public string Time { get; set; }
        public Nullable<int> Credits { get; set; }
        public Nullable<int> Reputation { get; set; }
    }
}
