//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asphalt_9_Materials.ViewModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grande
    {
        public int id { get; set; }
        public string Brand { get; set; }
        public string CarName { get; set; }
        public string CarClass { get; set; }
        public Nullable<int> Stars { get; set; }
        public string CarImage { get; set; }
        public Nullable<double> Refill { get; set; }
        public Nullable<int> Fuel { get; set; }
        public string CarType { get; set; }
        public string ReleaseDate { get; set; }
    
        public virtual Blueprint Blueprint { get; set; }
        public virtual EpicPart EpicPart { get; set; }
        public virtual MaxDetail MaxDetail { get; set; }
        public virtual RarePart RarePart { get; set; }
        public virtual StarRank StarRank { get; set; }
        public virtual StockDetail StockDetail { get; set; }
        public virtual UncommonPart UncommonPart { get; set; }
        public virtual Upgrade Upgrade { get; set; }
    }
}
