//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asphalt_9_Materials.ViewModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteTrack
    {
        public int id { get; set; }
        public string Location { get; set; }
        public string Track { get; set; }
        public Nullable<int> duration { get; set; }
        public string video { get; set; }
    }
}
