//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asphalt_9_Materials.ViewModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upgrade
    {
        public int id { get; set; }
        public Nullable<int> Stage1 { get; set; }
        public Nullable<int> Stage2 { get; set; }
        public Nullable<int> Stage3 { get; set; }
        public Nullable<int> Stage4 { get; set; }
        public Nullable<int> Stage5 { get; set; }
        public Nullable<int> Stage6 { get; set; }
        public Nullable<int> Stage7 { get; set; }
        public Nullable<int> Stage8 { get; set; }
        public Nullable<int> Stage9 { get; set; }
        public Nullable<int> Stage10 { get; set; }
        public Nullable<int> Stage11 { get; set; }
        public Nullable<int> Stage12 { get; set; }
        public Nullable<int> Stage13 { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Grande Grande { get; set; }
    }
}
